# fly.toml file generated for sentence-mining on 2022-05-02T15:47:32+03:00

app = "sentence-mining"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[build]
  image = "ghcr.io/ruslandoga/sentence-mining:754760885593f0fc96c99f1a65a25673110655c1"

[env]
  DB_PATH = "/data/m_prod.db"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source="sentence_data"
  destination="/data"

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 2000
    soft_limit = 1500
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
