name: build

on:
  pull_request:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  bench:
    name: build erlang release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: db
        run: mix run bench/db.exs
